Feat/matches ids ulid
laravel-json-api/core pull request #12
Opened 2023-07-13 15:37 UTC by Ashk2a

# Summary
Add possibility to match ULID.

2023-07-13 15:44 UTC, lindyhopchris requested changes
Thanks for this PR - looks like a good thing to add! Can you back out the change to the `.gitignore`? Ignoring IDE folders I'd expect in a global gitignore, not the project one.

Also, can you confirm where you got the regex for the ULID? Just so I can check it before merging and tagging.

2023-07-13 15:44 UTC, lindyhopchris commented on .gitignore
> +.idea/
Please back out this change.

2023-07-13 21:19 UTC, Ashk2a commented
> Thanks for this PR - looks like a good thing to add! Can you back out the change to the `.gitignore`? Ignoring IDE folders I'd expect in a global gitignore, not the project one.
> 
> Also, can you confirm where you got the regex for the ULID? Just so I can check it before merging and tagging.

I put information in the description. Like I said I didn't found an "official" regex for the ULID.
ChatGPT give me that : `^[0-9A-HJKMNP-TV-Z]{26}$`

2023-07-18 19:14 UTC, lindyhopchris commented
@Ashk2a thanks for the info about the regex- sorry I missed that in your original message.

I think we should match what Laravel does for route regexes for ULIDs. Looking at this docs:
https://laravel.com/docs/10.x/routing#parameters-regular-expression-constraints

There's a `whereUlid()` method when defining routes. That is here:
https://github.com/laravel/framework/blob/53b02b3c1d926c095cccca06883a35a5c6729773/src/Illuminate/Routing/CreatesRegularExpressionRouteConstraints.php#L48

Can you match the regex in your PR to the Laravel one? 

Sorry for the back and forth on this - only had time to look at the regex this evening. This is a great addition, so thanks for your time with it - I'm just making sure it's definitely right before merging!

2023-07-20 16:49 UTC, Ashk2a commented
> @Ashk2a thanks for the info about the regex- sorry I missed that in your original message.
> 
> I think we should match what Laravel does for route regexes for ULIDs. Looking at this docs: https://laravel.com/docs/10.x/routing#parameters-regular-expression-constraints
> 
> There's a `whereUlid()` method when defining routes. That is here: https://github.com/laravel/framework/blob/53b02b3c1d926c095cccca06883a35a5c6729773/src/Illuminate/Routing/CreatesRegularExpressionRouteConstraints.php#L48
> 
> Can you match the regex in your PR to the Laravel one?
> 
> Sorry for the back and forth on this - only had time to look at the regex this evening. This is a great addition, so thanks for your time with it - I'm just making sure it's definitely right before merging!

Thanks, very good idea to check Laravel directly!
Change made!

2023-07-20 17:07 UTC, lindyhopchris approved these changes

2023-07-20 17:08 UTC, merged